openapi: 3.0.0
info: 
  title: TL2106
  description: This is an API Documentation for the project of Tolls interoperability
  contact: 
    name: Dimitris Vasios 
    email: el19404@mail.ntua.gr
  version: 1.0.0
servers: 
- url: http://localhost:8080/interoperability/api/
  description: Base url
paths:
  /admin/healthcheck: 
    get: 
      description: Check end-to-end connectivity between client and database
      tags: 
        - Admin
      responses: 
        '200':
          description: Success
        '400': 
          description: Bad Request
        '500':
          description: Internal Server Error
  /admin/resetpasses: 
    post: 
      description: Initialization of the table Passes in the database
      tags: 
        - Admin
      responses: 
        '200':
          description: Success
        '400': 
          description: Bad Request
        '500':
          description: Internal Server Error
  /admin/resetstations: 
    post: 
      description: Initialization of the table Stations
      tags: 
        - Admin
      responses: 
        '200':
          description: Success
        '400': 
          description: Bad Request
        '500':
          description: Internal Server Error
  /admin/resetvehicles: 
    post: 
      description: Initialization of the table Vehicles
      tags: 
        - Admin
      responses: 
        '200':
          description: Success
        '400': 
          description: Bad Request
        '500':
          description: Internal Server Error
  /PassesPerStation/{stationID}/{date_from}/{date_to}: 
    get: 
      description: Return the Passes from the Station for the requested Period
      tags:
        - General
      parameters:
      - name: stationID
        in: path
        description: ID of the Station we want the results to be viewed
        required: true
        schema: 
          type: array
      - name: date_from
        in: path
        description: Date From
        required: true
        schema:
          type: string
      - name: date_to
        in: path
        description: Date To
        required: true
        schema: 
          type: string
      responses: 
        '200': 
          description: Station Passes returned
        '400': 
          description: Bad Request
        '402': 
          description: No Data
        '500':
          description: Internal Server Error
  /PassesAnalysis/{op1_ID}/{op2_ID}/{date_from}/{date_to}: 
    get: 
      description: List of Passes in Stations of Operator with op1_ID from other Operators with op2_ID
      tags:
        - General
      parameters:
      - name: op1_ID 
        in: path
        description: ID of the Stations Operator
        required: true
        schema: 
          type: array
      - name: op2_ID
        in: path
        description: ID of the Operator that its tags pass the Stations
        required: true
        schema:
          type: string
      - name: date_from
        in: path
        description: Date From
        required: true
        schema: 
          type: string
      - name: date_to 
        in: path
        description: Date To
        required: true
        schema: 
          type: string
      responses: 
        '200': 
          description: Passes Analysis returned
        '400': 
          description: Bad Request
        '402': 
          description: No Data
        '500':
          description: Internal Server Error
  /PassesCost/{op1_ID}/{op2_ID}/{date_from}/{date_to}: 
    get: 
      description: Number of passes and Cost from Operators with op2_iD to Operator with op1_ID 
      tags: 
        - General
      parameters:
      - name: op1_ID 
        in: path
        description: ID of the Stations Operator
        required: true
        schema: 
          type: array
      - name: op2_ID
        in: path
        description: ID of the Operator that its tags pass the tolls
        required: true
        schema:
          type: string
      - name: date_from
        in: path
        description: Date From
        required: true
        schema: 
          type: string
      - name: date_to 
        in: path
        description: Date To
        required: true
        schema: 
          type: string
      responses: 
        '200': 
          description: Passes Analysis returned
        '400': 
          description: Bad Request
        '402': 
          description: No Data
        '500':
          description: Internal Server Error
  /ChargesBy/{op_ID}/{date_from}/{date_to}: 
    get: 
      description: Passes and Cost to Operator with op_ID from the other Operators
      tags: 
        - General
      parameters:
      - name: op_ID
        in: path
        description: ID of the Operator 
        required: true
        schema:
          type: string
      - name: date_from
        in: path
        description: Date From
        required: true
        schema: 
          type: string
      - name: date_to 
        in: path
        description: Date To
        required: true
        schema: 
          type: string
      responses: 
        '200': 
          description: Passes Analysis returned
        '400': 
          description: Bad Request
        '402': 
          description: No Data
        '500':
          description: Internal Server Error